######################################################
##                                                  ##
##               SSBProxyBridge Module              ##
##                Developed by Ome_R                ##
##                                                  ##
######################################################


# The name of the server the module is running on.
# This name should be the same as the one configured in your BungeeCord / Velocity configuration,
# as this name is later being used to teleport players between servers.
server: 'server'

# The name of the server of the spawn. This name can be the same as the one above.
# This name should be the same as the one configured in your BungeeCord / Velocity configuration,
# as this name is later being used to teleport players between servers.
spawn-server-name: 'spawn'

# The module uses an external messaging service in order to communicate and synchronize data
# between the servers. In this section you should configure the options for the service.
messaging-service:
  # The type of service to use for messaging.
  # This type can be Redis or RabbitMQ.
  type: 'redis'
  # The name of the channel to use for messaging service.
  # This should be a unique channel name that is not taken by any other consumers.
  # The names of the channels can be identical.
  channels:
    data: 'ssbproxybridge-data'
    actions: 'ssbproxybridge-actions'

  # Connection settings for Redis
  redis:
    # The host name of the redis server to connect to.
    host: 'localhost'
    # The port of the redis server.
    port: 6379
    # The authentication credentials for the redis client.
    username: ''
    password: ''

  # Connection settings for RabbitMQ
  rabbitmq:
    # The host name of the rabbitmq server to connect to.
    host: 'localhost'
    # The port of the rabbitmq server.
    port: 5672
    # The virtual host to use.
    virtual-host: '/'
    # The authentication credentials for the rabbitmq client.
    username: 'guest'
    password: 'guest'